pos1:
   x: 0
   y: 0
   z: 0
   pitch: 0
   yaw: 0

pos2:
   x: 0
   y: 0
   z: 0
   pitch: 0
   yaw: 0
   
items:
   - iron_sword 1
   - cooked_beef 5
   
helmet: iron_helmet
chestplate: iron_chestplate
leggings: iron_leggings
boots: iron_boots