name: DuelArena
main: io.github.toomanybugs.DuelArena.DuelArena
version: 0.0.1-SNAPSHOT
api-version: 1.16
author: toomanybugs
commands:
   challenge:
      description: Challenge the player to a duel.
      usage: /challenge player
      permission: DuelArena.challenge
      permission-message: You don't have permission to challenge other players.
   accept:
      description: Accept a challenge from a player.
      usage: /accept
      permission: DuelArena.challenge
      permission-message: You don't have permission to accept challenges.
   decline:
      description: Decline a challenge from a player.
      usage: /decline
      permission: DualArena.challenge
      permission-message: You don't have permission to decline challenges.
   duelpos:
      description: Set positions for challengers to appear when the duel starts.
      usage: /duelpos 1
      permission: DuelArena.admin
      permission-message: You don't have permission to change the duel positions.